spring.application.name=proxy
server.port=8090

spring.data.redis.host=192.168.194.250
spring.data.redis.port=6379
spring.data.redis.timeout=2000

spring.kafka.listener.auto-startup=true
spring.kafka.bootstrap-servers=192.168.194.250:9092
spring.kafka.consumer.group-id=464aa31e-1ca8-41d6-b3ff-583b5cfd7c29
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

catedra.base-url=http://192.168.194.250:8080
backend.base-url=http://localhost:8080
catedra.auth-token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJjb3MiLCJleHAiOjE4NTIyMjAyNTYsImF1dGgiOiJST0xFX1VTRVIiLCJpYXQiOjE3NjU4MjAyNTZ9.U1M-qmUu2qSCw7W0sV1bNDfqWZW-6s4j1AeMwXQw9IyUthxeEaseKTqdwlwzL_v37KPGy6zr44eTGSDd1s1UtQ




