spring.application.name=backend

proxy.base-url=http://localhost:8090

spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

catedra.base-url=http://192.168.194.250:8080
catedra.auth-token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJjb3MiLCJleHAiOjE4NTE3MDgzOTYsImF1dGgiOiJST0xFX1VTRVIiLCJpYXQiOjE3NjUzMDgzOTZ9.LhaYoSAkZGzJiG2YAsqz336fW_uGw8SL6N94OGo6WU8L5bt_SFCPIs5qGlbxk2PaY2VKbmKkl1GSDyRJeZKUMw

