spring.application.name=backend

proxy.base-url=http://localhost:8090

spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

catedra.base-url=http://192.168.194.250:8080
catedra.auth-token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJjb3MiLCJleHAiOjE4NTIyMjAyNTYsImF1dGgiOiJST0xFX1VTRVIiLCJpYXQiOjE3NjU4MjAyNTZ9.U1M-qmUu2qSCw7W0sV1bNDfqWZW-6s4j1AeMwXQw9IyUthxeEaseKTqdwlwzL_v37KPGy6zr44eTGSDd1s1UtQ

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=2000